spring.profiles.active=dev

spring.application.name=subasta-app-back
server.port=8080


spring.datasource.url=jdbc:postgresql://ep-odd-firefly-apjaj6qo-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_loYv85LDTEXS
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (IMPORTANTE PARA NEON)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=15000
spring.datasource.hikari.connection-timeout=60000

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# evita problemas de metadata con postgres serverless
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT
jwt.secret=subastaapp-secret-key-muy-larga-para-seguridad-256bits-minimo-requerido
jwt.expiration=86400000

# CORS
spring.mvc.cors.allowed-origins=*

# API base path
server.servlet.context-path=/api/v1

subasta.tiempo.item.segundos = 60