spring.profiles.active=dev

spring.application.name=subasta-app-back
server.port=8080


spring.datasource.url=jdbc:postgresql://ep-small-wildflower-ac5xfsum-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_i0eDgHELrX5R
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=subastaapp-secret-key-muy-larga-para-seguridad-256bits-minimo-requerido
jwt.expiration=86400000

# CORS
spring.mvc.cors.allowed-origins=*

# API base path
server.servlet.context-path=/api/v1
