### Crear un nuevo usuario
POST http://localhost:8080/api/v1/usuarios/registro
Content-Type: application/json

{
  "documento": "41234567",
  "nombre": "Lucas",
  "apellido": "Perez",
  "pais": "Argentina",
  "domicilio": "Caballito",
  "password": "123123",
  "fotoDocumentoFrente": "data:image/webp;base64,UklGRkJJAABXRUJQVlA4WAoAAAAIAAAADAIAXQEAVlA4IGJIAADQMAGdASoNAl4BPnU2lkkkoqyspDY5uZAOiU1B3m4E21M6NNUaodARCtj2DePd7pCYC7m98P7f/zPEG63+ij/sPVqwIu1vsAcZnP1/5PoO/WXT9/1PIl9n21RQLq92s7fqn0g+y/xH7I6SPfP+r52/Uv/h+5T4rf8r24/r72JP1u6nnnL/ab1Sf+d7GP736mf9j/1/XTejd+y/",
  "fotoDocumentoDorso": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAIQAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAAHRyWFlaAAABZAAAABRnWFlaAAABeAAAABRiWFlaAAABjAAAABRyVFJDAAABoAAAAChnVFJDAAABoAAAAChiVFJDAAABoAAAACh3dHB0AAAByAAAABRjcHJ0AAAB3AAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAFgAAAAcAHMAUgBHAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "fotoPerfil": "",
  "medioPagos": [
    {
      "tipo": "TARJETA",
      "numeroTarjeta": "4545123456789012",
      "nombreTitular": "Lucas",
      "fechaVencimento": "12/29",
      "cvv": "123"
    },
    {
      "tipo": "CHEQUE",
      "monto": 500000.0,
      "bancoEmisor": "Banco Galicia",
      "titularCheque": "Lucas",
      "numeroCheque": "78901234",
      "fechaEmision": "2026-05-14",
      "fotoTitularCheque": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD_foto_cheque_certificado..."
    }
  ]
}