### Endpoint para agregar un medio de pago asociado a un usuario
POST http://localhost:8080/api/v1/usuarios/me/medios-pago
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MjIxNTgzMyIsImlhdCI6MTc3OTY4NTUzOSwiZXhwIjoxNzc5NzcxOTM5fQ.m453_iNzhfaSI92MbMrinSjANi-w4bjlfm9NLhjHPG0

{
  "tipo": "CUENTA",
  "titularCuenta": "Luciano Cabral",
  "tipoCuenta": "Caja de Ahorro",
  "moneda": "Dólares Americanos",
  "cbuAlias": "0987654321"
}
###